### YamlMime:ManagedReference
items:
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor
  commentId: T:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor
  id: IPlatformSpecificConfigEditor
  parent: PlayEveryWare.EpicOnlineServices
  children:
  - PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.Awake
  - PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.GetNameForMenu
  - PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.LoadConfigFromDisk
  - PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.OnGUI
  - PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.SaveToJSONConfig(System.Boolean)
  langs:
  - csharp
  - vb
  name: IPlatformSpecificConfigEditor
  nameWithType: IPlatformSpecificConfigEditor
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor
  type: Interface
  source:
    id: IPlatformSpecificConfigEditor
    path: ''
    startLine: 3788
  assemblies:
  - cs.temp.dll
  namespace: PlayEveryWare.EpicOnlineServices
  syntax:
    content: public interface IPlatformSpecificConfigEditor
    content.vb: Public Interface IPlatformSpecificConfigEditor
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.GetNameForMenu
  commentId: M:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.GetNameForMenu
  id: GetNameForMenu
  parent: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor
  langs:
  - csharp
  - vb
  name: GetNameForMenu()
  nameWithType: IPlatformSpecificConfigEditor.GetNameForMenu()
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.GetNameForMenu()
  type: Method
  source:
    id: GetNameForMenu
    path: ''
    startLine: 3790
  assemblies:
  - cs.temp.dll
  namespace: PlayEveryWare.EpicOnlineServices
  syntax:
    content: string GetNameForMenu()
    return:
      type: System.String
    content.vb: Function GetNameForMenu As String
  overload: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.GetNameForMenu*
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.Awake
  commentId: M:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.Awake
  id: Awake
  parent: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor
  langs:
  - csharp
  - vb
  name: Awake()
  nameWithType: IPlatformSpecificConfigEditor.Awake()
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.Awake()
  type: Method
  source:
    id: Awake
    path: ''
    startLine: 3792
  assemblies:
  - cs.temp.dll
  namespace: PlayEveryWare.EpicOnlineServices
  syntax:
    content: void Awake()
    content.vb: Sub Awake
  overload: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.Awake*
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.LoadConfigFromDisk
  commentId: M:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.LoadConfigFromDisk
  id: LoadConfigFromDisk
  parent: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor
  langs:
  - csharp
  - vb
  name: LoadConfigFromDisk()
  nameWithType: IPlatformSpecificConfigEditor.LoadConfigFromDisk()
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.LoadConfigFromDisk()
  type: Method
  source:
    id: LoadConfigFromDisk
    path: ''
    startLine: 3794
  assemblies:
  - cs.temp.dll
  namespace: PlayEveryWare.EpicOnlineServices
  syntax:
    content: void LoadConfigFromDisk()
    content.vb: Sub LoadConfigFromDisk
  overload: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.LoadConfigFromDisk*
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.SaveToJSONConfig(System.Boolean)
  commentId: M:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.SaveToJSONConfig(System.Boolean)
  id: SaveToJSONConfig(System.Boolean)
  parent: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor
  langs:
  - csharp
  - vb
  name: SaveToJSONConfig(Boolean)
  nameWithType: IPlatformSpecificConfigEditor.SaveToJSONConfig(Boolean)
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.SaveToJSONConfig(System.Boolean)
  type: Method
  source:
    id: SaveToJSONConfig
    path: ''
    startLine: 3796
  assemblies:
  - cs.temp.dll
  namespace: PlayEveryWare.EpicOnlineServices
  syntax:
    content: void SaveToJSONConfig(bool prettyPrint)
    parameters:
    - id: prettyPrint
      type: System.Boolean
    content.vb: Sub SaveToJSONConfig(prettyPrint As Boolean)
  overload: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.SaveToJSONConfig*
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.OnGUI
  commentId: M:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.OnGUI
  id: OnGUI
  parent: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor
  langs:
  - csharp
  - vb
  name: OnGUI()
  nameWithType: IPlatformSpecificConfigEditor.OnGUI()
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.OnGUI()
  type: Method
  source:
    id: OnGUI
    path: ''
    startLine: 3798
  assemblies:
  - cs.temp.dll
  namespace: PlayEveryWare.EpicOnlineServices
  syntax:
    content: void OnGUI()
    content.vb: Sub OnGUI
  overload: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.OnGUI*
references:
- uid: PlayEveryWare.EpicOnlineServices
  commentId: N:PlayEveryWare.EpicOnlineServices
  name: PlayEveryWare.EpicOnlineServices
  nameWithType: PlayEveryWare.EpicOnlineServices
  fullName: PlayEveryWare.EpicOnlineServices
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.GetNameForMenu*
  commentId: Overload:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.GetNameForMenu
  name: GetNameForMenu
  nameWithType: IPlatformSpecificConfigEditor.GetNameForMenu
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.GetNameForMenu
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.Awake*
  commentId: Overload:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.Awake
  name: Awake
  nameWithType: IPlatformSpecificConfigEditor.Awake
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.Awake
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.LoadConfigFromDisk*
  commentId: Overload:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.LoadConfigFromDisk
  name: LoadConfigFromDisk
  nameWithType: IPlatformSpecificConfigEditor.LoadConfigFromDisk
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.LoadConfigFromDisk
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.SaveToJSONConfig*
  commentId: Overload:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.SaveToJSONConfig
  name: SaveToJSONConfig
  nameWithType: IPlatformSpecificConfigEditor.SaveToJSONConfig
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.SaveToJSONConfig
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.OnGUI*
  commentId: Overload:PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.OnGUI
  name: OnGUI
  nameWithType: IPlatformSpecificConfigEditor.OnGUI
  fullName: PlayEveryWare.EpicOnlineServices.IPlatformSpecificConfigEditor.OnGUI
